name: ci 
on:
  push:
    tags:
      - '**'
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - run: pip install mkdocs mkdocs-material mike
      - run: pip install pillow cairosvg
      # - run: git fetch origin gh-pages --depth=1
      - run: mike deploy --push --update-aliases $GITHUB_REF_NAME latest
      - run: mike set-default latest